### PR TITLE
chore: update org name

### PR DESCRIPTION
**Pull request by Readpato**
As title says, update org name wherever possible

### CODE REVIEW

**Comment by TheJoin95** [comment]
@Readpato please verify ci

**Comment by Readpato** [comment]
Mhmm, there seems to be something weird here, because I haven't modified the files were the pipeline crashed. Maybe the project owners know how to bypass this? @LobeTia

cc @TheJoin95

**Comment by TheJoin95** [comment]
Sorry, It was my fault. In this project the ci Is failing. Approving as it's not affecting it

**Review by TheJoin95 — APPROVED** [review]
You can merge

**Pull request merged**
